services:
  web:
    build: .
    ports:
      - "127.0.0.1:8100:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    logging:
      driver: json-file
      options:
        tag: "{{.Name}}"

  db:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "127.0.0.1:5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d antifraud"]
      interval: 5s
      timeout: 5s
      retries: 5

  loki:
    image: grafana/loki:2.9.4
    ports:
      - "127.0.0.1:3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/loki
      - ./loki-config.yaml:/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.4
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:10.4.2
    ports:
      - "127.0.0.1:3001:3000"
    depends_on:
      - loki
    environment:
      GF_SERVER_DOMAIN: antifraud-aadov.duckdns.org
      GF_SERVER_ROOT_URL: https://antifraud-aadov.duckdns.org/
      GF_SERVER_PROTOCOL: http
      GF_SECURITY_COOKIE_SECURE: "true"
      GF_SECURITY_COOKIE_SAMESITE: lax
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_AUTH_ANONYMOUS_ENABLED: "false"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning:ro
      - ./dashboards:/var/lib/grafana/dashboards:ro
    env_file:
      - .env

  seeder:
    image: curlimages/curl:latest
    depends_on:
      - web
    volumes:
      - ./seed.sh:/seed.sh
    entrypoint: ["sh", "/seed.sh"]

volumes:
  grafana_data:
  loki_data:
