{
 "title": "Antifraud Lab",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": " География атак",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum by (country) (count_over_time({job=\"docker\"} |= \"login_risk_evaluated\" | json | __error__=\"\" | line_format \"{{.log}}\" | json | decision=\"BLOCK\" [5m]))"
    }
   ]
  },
  {
   "title": "TOP IP BLOCK:",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (ip) (count_over_time({job=\"docker\"} |= \"login_risk_evaluated\" | json | __error__=\"\" | line_format \"{{.log}}\" | json | decision=\"BLOCK\" [5m]))"
    }
   ]
  },
  {
   "title": "Block|2FA|Allowed.",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum by (decision) (count_over_time({job=\"docker\"} |= \"login_risk_evaluated\" | json | __error__=\"\" | line_format \"{{.log}}\" | json | decision=~\"ALLOW|2FA|BLOCK\" [1m]))"
    }
   ]
  },
  {
   "title": " BLOCK rate %",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"docker\"} |= \"login_risk_evaluated\" | json | __error__=\"\" | line_format \"{{.log}}\" | json | decision=\"BLOCK\" [5m]))\r\n/\r\nsum(count_over_time({job=\"docker\"} |= \"login_risk_evaluated\" | json | __error__=\"\" | line_format \"{{.log}}\" | json [5m]))\r\n* 100",
     "legendFormat": "BLOCK rate %"
    }
   ]
  },
  {
   "title": "TOP users BLOCK",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "expr": "sum by (user_id) (count_over_time({job=\"docker\"} |= \"login_risk_evaluated\" | json | __error__=\"\" | line_format \"{{.log}}\" | json | decision=\"BLOCK\" [5m]))"
    }
   ]
  }
 ]
}